# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-SSLify
version:      0.05
version_from: lib/POE/Component/SSLify.pm
installdirs:  site
requires:
    Net::SSLeay:                   1.30

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
