---
abstract: 'SSL in the world of POE made easy'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
build_requires:
  POE: 1.267
  POE::Component::Client::TCP: 0
  POE::Component::Server::TCP: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SSLify
provides:
  POE::Component::SSLify:
    file: lib/POE/Component/SSLify.pm
    version: 0.20
  POE::Component::SSLify::ClientHandle:
    file: lib/POE/Component/SSLify/ClientHandle.pm
    version: 0.20
  POE::Component::SSLify::ServerHandle:
    file: lib/POE/Component/SSLify/ServerHandle.pm
    version: 0.20
requires:
  Net::SSLeay: 1.36
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=POE-Component-SSLify
  homepage: http://search.cpan.org/dist/POE-Component-SSLify
  license: http://dev.perl.org/licenses/
  repository: http://github.com/apocalypse/perl-poe-sslify
version: 0.20
